Instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagram/', include("app.urls")),
    path('portfolio/', include("Portfolio.urls")),
    path('portfolio/polls', include("polls.urls")),


]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Portfolio/urls.py
from django.urls import path, include
from . import views


app_name = 'portfolio'

urlpatterns = [

    path('home',views.homeView, name='home'),
    path('about',views.aboutView, name='about'),
    path('projects',views.projectView, name='projects'),
    path('contact',views.contactView, name='contact'),
    path('tasks/api', views.apiView, name="api"),
    path('tasks/calculator', views.calculatorView, name="calculator"),
    path('tasks/flexbox', views.flexboxView, name="flexbox"),
    path('tasks/sql', views.sqlView, name="sql"),
    path('tasks/website', views.websiteView, name="website"),
    path('tasks/flexbox_advanced', views.flex_advView, name="flex_adv"),
    path('tasks/login_page', views.loginView, name="login_page"),


]

app/urls.py
from django.urls import path, include
from . import views
from . form import CustomAuthForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

app_name = 'app'

urlpatterns = [

    path('signup',views.signup, name='signup'),
    path('login', auth_views.LoginView.as_view(template_name='registration/login.html',authentication_form=CustomAuthForm), name='user_login'),
    path('home/', views.HomeView.as_view(),name='home'),
    path('user/post', views.addPostView.as_view(),name='addPost'),
    path('user/profile/<int:pk>', views.ShowProfileView.as_view(), name='profile'),
    path('user/profile/edit/', views.UpdateProfileView, name='editProfile'),
    path('user/profile/<int:pk>/delete', views.DeleteProfileView.as_view(), name='delete_profile'),
    path('user/post/<int:pk>', views.ShowPostView.as_view(), name='post'),
    path('user/post/<int:pk>/delete', views.DeletePostView.as_view(), name='delete_post'),
    path('user/post/<int:pk>/edit', views.UpdatePostView.as_view(), name='edit_post'),
    path('home/', include('django.contrib.auth.urls'),name="logout"),
    path('user/home/like', views.LikeView, name="like"),
    path('user/home/follow', views.FollowView, name="follow"),
    path('user/home/comment/<int:pk>', views.CommentView.as_view(), name="comment"),

]


#path('', include('django.contrib.auth.urls'))

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('',views.index, name="index"),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Portfolio/models.py
from django.db import models

# Create your models here.

Portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse

def homeView(request):
    return render(request, "portfolio/index.html")

def aboutView(request):
    return render(request, "portfolio/about.html")

def projectView(request):
    return render(request, "portfolio/project.html")

def contactView(request):
    return render(request, "portfolio/contact.html")

def apiView(request):
    return render(request, "portfolio/tasks/api.html")

def calculatorView(request):
    return render(request, "portfolio/tasks/calculator.html")

def flexboxView(request):
    return render(request, "portfolio/tasks/flexbox.html")

def sqlView(request):
    return render(request, "portfolio/tasks/sql.html")

def websiteView(request):
    return render(request, "portfolio/tasks/website.html")

def flex_advView(request):
    return render(request, "portfolio/tasks/flex_adv.html")

def loginView(request):
    return render(request, "portfolio/tasks/login.html")

Portfolio/templates/portfolio/about.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link href="{% static '/portfolio/CSS/about.css' %}" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/f91dab228a.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
    <div class="nav">
        <a href="{% url 'portfolio:home' %}"><img id="exp" src="{% static '/portfolio/images/explorin_logo.png' %}" width=150px height=50px></a>
        <div class="tabs">
            <i id="toggler" class="fa fa-bars fa-lg" style="color:rgb(100, 130, 168)" aria-hidden="true"></i>
            <div id="nav-box">
                <a class="current" href="{% url 'portfolio:about' %}"><div >ABOUT</div></a>
                <a href="{% url 'portfolio:projects' %}"><div>PROJECTS</div></a>
                <a href="{% url 'portfolio:contact' %}"><div>CONTACTS</div></a>
            </div>
        </div>
    </div>

    <div class="main">    
        <img id="image" src="{% static '/portfolio/images/image.jpg' %}" height=220px weight =220px>
        <div class="content">

            <h1>About</h1>
            <div id="accordion">
                <h3>Introduction</h3>
                <div>
                  <p>I am Vaidehi Atpadkar. I am currently studying Engineering Physics 
                    at IIT Mandi.
                    But I also want to explore my interest in Software Development.</p>
                </div>
                <h3>Education</h3>
                    <div>
                      <table>
                          <tr>
                              <th>Class</th>
                              <th>School</th>
                              <th>Percentage</th>
                          </tr>
                          <tr>
                              <td>X</td>
                              <td>R.M.D.E.M.S</td>
                              <td>98</td>
                          </tr>
                          <tr>
                              <td>XII</td>
                              <td>Fergusson College Pune</td>
                              <td>85.3</td>
                          </tr>
                      </table>
                    </div>
                <h3>Reasons to join</h3>
                <div>
                  <p>Till now, I have tried a few things in web development. But nothing kept me going in the long run.
                    I have really liked a few things, but I couldn't continue doing them and explore more.
                    I guess this is due to lack of systematic guidance. So I want to properly explore and understand several aspects of 
                    software development and find my true interests.
                  </p>
                </div>
                <h3>Journey till now</h3>
                  <div>
                    <p>My journey till now with Explorin has been really wonderful. I have really enjoyed and liked all the 
                        things which I have done here; be it learning from resources, understanding new concepts, doing tasks, 
                        interacting with all the mentors, industrial experts and all the explorers. Each day I am getting to learn 
                        something new. So, I am really looking forward to the program and wish to learn and explore more.  
                    </p>
                    </div>
                <h3>Technologies learnt</h3>
                  <div>
                    <p>Frontend - HTML, CSS, Jquery basics<br>Backend - SQL, PHP</p>
                  </div>
          
                  
            </div>
        </div>        
    </div>

<script>
    $( "#accordion" ).accordion({heightStyle: "content",active: false, collapsible:true});
</script>
<script>

$( document ).ready(function() {

    let display=false
    $("#toggler").on('click', function() {

        if(display === false){
            display = true;
            $("#nav-box").slideDown("slow");

            $(this).removeClass("fa fa-bars");

            $(this).addClass("fa fa-times");

        }
        else{
            display = false;
            $("#nav-box").slideUp("slow");

            $(this).removeClass("fa fa-times");

            $(this).addClass("fa fa-bars");

        }

    })

})
</script>

</body>
</html>

Portfolio/templates/portfolio/contact.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
    <link href="{% static '/portfolio/CSS/contact.css' %}" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/f91dab228a.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>

</head>

<body>

    <div class="big_container">
        <div class="nav">
            <a href="{% url 'portfolio:home' %}"><img id="exp" src="{% static '/portfolio/images/explorin_logo.png' %}" width=150px height=50px></a>
            <div class="tabs">
                <i id="toggler" class="fa fa-bars fa-lg" style="color:rgb(100, 130, 168)" aria-hidden="true"></i>
                <div id="nav-box">
                    <a href="{% url 'portfolio:about' %}"><div >ABOUT</div></a>
                    <a href="{% url 'portfolio:projects' %}"><div>PROJECTS</div></a>
                    <a class="current" href="{% url 'portfolio:contact' %}"><div>CONTACTS</div></a>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="main">

                <h1>Contact</h1>
                <p>If you want to contact me, you can reach me via:</p>

                <ul>
                    <li>Whatsapp: <span>7057648018</span></li>
                    <li>Gmail: <span>vaidehiatpadkar1@gmail.com</span></li>
                    <li>Facebook: <span>https://www.facebook.com/vaidehi.atpadkar.9</span></li>
                    <li>LinkedIn: <span>https://www.linkedin.com/in/vaidehi-atpadkar-2755771b2/</span></li>
                </ul>

            </div>

            <footer>
                    <a href="#">
                    <i class="fab fa-google-plus-g"></i>
                    </a>
                    <a href="https://www.facebook.com/vaidehi.atpadkar.9">
                    <i class="fab fa-facebook-square" ></i>
                    </a>
                    <a href="https://www.linkedin.com/in/vaidehi-atpadkar-2755771b2/">
                    <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="#">
                    <i class="fas fa-envelope"></i>
                    </a>
                    <a href="#">
                    <i class="fab fa-instagram" ></i>
                    </a>
            </footer>

            <div class="design"></div>
            <div class="design2"></div>

        </div>
    </div>
    

    <script>

        $( document ).ready(function() {
        
            let display=false
            $("#toggler").on('click', function() {
        
                if(display === false){
                    display = true;
                    $("#nav-box").slideDown("slow");
        
                    $(this).removeClass("fa fa-bars");
        
                    $(this).addClass("fa fa-times");
        
                }
                else{
                    display = false;
                    $("#nav-box").slideUp("slow");
        
                    $(this).removeClass("fa fa-times");
        
                    $(this).addClass("fa fa-bars");
        
                }
        
            })
        
        })
</script>


</body>
</html>

Portfolio/templates/portfolio/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link href="{% static '/portfolio/CSS/home.css' %}" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/f91dab228a.js"></script>
</head>

<body>
    
    <div class="main">  
        <div class="logo">
            <a href="{% url 'portfolio:home' %}"><img id="exp" src="{% static '/portfolio/images/explorin_logo.png' %}" width=150px height=50px></a>
        </div>  

        <div class="insta"> 
            <div>
                <pre>Link to <b><a href="{% url 'app:signup' %}" >Instagram</a></b> the master project</pre>
                <small>(You can signup, login and then see it!)</small> <i class="far fa-grin-alt"></i>
                
            </div>

        </div>

        <div class="content">
            <img id="image" src="{% static '/portfolio/images/image.jpg' %}" height=220px weight=220px>

            <h1>Vaidehi Atpadkar</h1>
            <p>SOFTWARE DEVELOPMENT EXPLORATION PROGRAM</p>

            <div class="nav">
                <a href="{% url 'portfolio:about' %}">ABOUT</a>
                <a href="{% url 'portfolio:projects' %}">PROJECTS</a>
                <a href="{% url 'portfolio:contact' %}">CONTACTS</a>
            </div>

            <div class="social">
                <a href="#">
                <i class="fab fa-google-plus-g" ></i>
                </a>
                <a href="https://www.facebook.com/vaidehi.atpadkar.9">
                <i class="fab fa-facebook-square" ></i>
                </a>
                <a href="https://www.linkedin.com/in/vaidehi-atpadkar-2755771b2/">
                <i class="fab fa-linkedin" ></i>
                </a>
                <a href="#">
                <i class="fas fa-envelope" ></i>
                </a>
                <a href="#">
                <i class="fab fa-instagram" ></i>
                </a>
            </div>

        </div>
        
        <div class="design"></div>
        <div class="design2"></div>

        

    </div>

</body>
</html>

Portfolio/templates/portfolio/project.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projects</title>
    <script src="https://kit.fontawesome.com/f91dab228a.js"></script>
    <link href="{% static '/portfolio/CSS/project.css' %}" rel="stylesheet" type="text/css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>

</head>

<body>
    <div class="nav">
        <a href="{% url 'portfolio:home' %}"><img id="exp" src="{% static '/portfolio/images/explorin_logo.png' %}" width=150px height=50px></a>
        <div class="tabs">
            <i id="toggler" class="fa fa-bars fa-lg" style="color:rgb(100, 130, 168)" aria-hidden="true"></i>
            <div id="nav-box">
                <a href="{% url 'portfolio:about' %}"><div >ABOUT</div></a>
                <a class="current" href="{% url 'portfolio:projects' %}"><div>PROJECTS</div></a>
                <a href="{% url 'portfolio:contact' %}"><div>CONTACTS</div></a>
            </div>
        </div>
    </div>

    <div class="main">

        <h1>Projects</h1>
        <p id='text'>Given below are some projects or tasks completed by me at Explorin. <small>(You can see them by clicking on the project's name.)</p>

        <div class="content">
            <div class="task">
                <a href="{% url 'portfolio:flexbox' %}"><h3>Flexbox</h3></a>
                <div class="day">
                    <p>DAY 3 Task</p>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">Made a cool flexbox. This task was a little challenging as it was not very straight-forward
                        and made us ponder how to make different flex-containers and decide their orientations.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">HTML and CSS.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">Approximately 4-5 hours.</p>
                </div>
            </div>

            <div class="task">
                    <a href="{% url 'portfolio:calculator' %}"><h3>Calculator</h3></a>
                    <div class="day">
                        <p>DAY 4 Task</p>
                    </div>
            </div>

            <div class="container">
                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">Made a simple calculator which gives contribution that every member of any group should 
                        make given total amount of money that the group has to pay. Well, it can come in handy for people bad at division.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">HTML, CSS and JQuery.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">Approximately 3-4 hours.</p>
                </div>
            </div>

            <div class="task">
            
                <a href="{% url 'portfolio:website' %}"><h3>My First Website <span>| Thanks to explorin</span></h3></a>
                <div class="day">
                    <p>WEEK 1 Task</p>
                </div>

            </div>
            <div class="container">

                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">A fully static but attractive website with super cool home background, navigation bar(made with flexbox), 
                        beautiful template, social media footer.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">HTML and CSS.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">Approximately 10-12 hours.</p>
                </div>
            </div>

            <div class="task">
            
                <a href="{% url 'portfolio:sql' %}"><h3>SQL</h3></a>
                <div class="day">
                    <p>DAY 9 Task</p>
                </div>

            </div>
            <div class="container">

                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">Performed various SQL queries on a database by installing MYSQL. Got to know about 
                        how databases are made, updated and maintained and also how easily and skillfully required information can be 
                        obtained from databases. 
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">SQL</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">About 2-3 hours.</p>
                </div>
            </div>

            <div class="task">
            
                <a href="{% url 'portfolio:flex_adv' %}"><h3>Flexbox Advance</h3></a>
                <div class="day">
                    <p>DAY 11 Task</p>
                </div>

            </div>
            <div class="container">

                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">Here I modified my previously made flexbox by using JQuery. JQuery added amazing effects to it 
                        like swapping of colors on hovering, changing background of one of the flex-items on clicking it and appending 
                        some text in a flex-item on clicking on some other item.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">HTML, CSS and JQuery.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">About 3-4 hours.</p>
                </div>
            </div>

            <div class="task">
            
                <a href="{% url 'portfolio:api' %}"><h3>Youtube API</h3></a>
                <div class="day">
                    <p>DAY 11 Task</p>
                </div>

            </div>
            <div class="container">

                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">This task required to make use of Youtube API and fetch videos from youtube using AJAX JQuery.
                        Got to learn how to access the console responses and use it. Here, I have fetched youtube videos from 3 channels.
                        This could really be used to quickly access the latest uploads from our favorite youtube channels.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">HTML, CSS and JQuery.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">About 8-9 hours.</p>
                </div>
            </div>

            <div class="task">
            
                <a href="{% url 'portfolio:login_page' %}"><h3>My First Login Page</h3></a>
                <div class="day">
                    <p>DAY 12 Task</p>
                </div>

            </div>
            <div class="container">

                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">This task included frontend as well as databases. Using PhpMyAdmin I could make a login form 
                        which would allow user to login after properly validating his/ her credentials; or make a registration 
                        if he/she doesn't has an account by taking input and verifying if the username doesn't already exist. It also involved 
                        concepts of sessions and connections with databases.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">HTML, CSS, PHP, SQL.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">About 4-5 hours.</p>
                </div>
            </div>

            <div class="task">
            
                <a href="{% url 'polls:index' %}"><h3>First Django app - Polls App</h3></a>
                <div class="day">
                    <p>DAY 17 Task</p>
                </div>

            </div>
            <div class="container">

                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">Polls app is my first Django app. I got to know about how Django works and how amazing it is. Polls is 
                        a very simple app which displays some questions and takes input from people and stores them in the database.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">Django, HTML, CSS.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">About 4-5 hours.</p>
                </div>
            </div>

            <div class="task">
            
                <a href="{% url 'app:signup' %}"><h3>The master project - INSTAGRAM (replica)</h3></a>
                <div class="day">
                    <p>DAY 30 Task</p>
                </div>

            </div>
            <div class="container">

                <div class="row">
                    <p class="title">Description:</p>
                    <p class="text">This master project involved replicating a social media site, Instagram, using Django. It isn't an exact replica though.
                        This project helped to understand how various things are managed in a big websie as such; user authentication, profiles, functionalities 
                        like like, comment, followers, edits, etc. Django really makes it easier to include these things in a awebsite.
                    </p>
                </div>
                <div class="row">
                    <p class="title">Technologies used:</p>
                    <p class="text">Django, HTML, CSS.</p>
                </div>
                <div class="row">
                    <p class="title">Time taken:</p>
                    <p class="text">About 1 week.</p>
                </div>
            </div>

        </div>

      
    </div>

    <script>

        $( document ).ready(function() {
        
            let display=false
            $("#toggler").on('click', function() {
        
                if(display === false){
                    display = true;
                    $("#nav-box").slideDown("slow");
        
                    $(this).removeClass("fa fa-bars");
        
                    $(this).addClass("fa fa-times");
        
                }
                else{
                    display = false;
                    $("#nav-box").slideUp("slow");
        
                    $(this).removeClass("fa fa-times");
        
                    $(this).addClass("fa fa-bars");
        
                }
        
            })
        
        })
        </script>

</body>
</html>