Instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagram/', include("app.urls")),
    path('portfolio/', include("Portfolio.urls")),
    path('portfolio/polls', include("polls.urls")),


]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include
from . import views
from . form import CustomAuthForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

app_name = 'app'

urlpatterns = [

    path('signup',views.signup, name='signup'),
    path('login', auth_views.LoginView.as_view(template_name='registration/login.html',authentication_form=CustomAuthForm), name='user_login'),
    path('home/', views.HomeView.as_view(),name='home'),
    path('user/post', views.addPostView.as_view(),name='addPost'),
    path('user/profile/<int:pk>', views.ShowProfileView.as_view(), name='profile'),
    path('user/profile/edit/', views.UpdateProfileView, name='editProfile'),
    path('user/profile/<int:pk>/delete', views.DeleteProfileView.as_view(), name='delete_profile'),
    path('user/post/<int:pk>', views.ShowPostView.as_view(), name='post'),
    path('user/post/<int:pk>/delete', views.DeletePostView.as_view(), name='delete_post'),
    path('user/post/<int:pk>/edit', views.UpdatePostView.as_view(), name='edit_post'),
    path('home/', include('django.contrib.auth.urls'),name="logout"),
    path('user/home/like', views.LikeView, name="like"),
    path('user/home/follow', views.FollowView, name="follow"),
    path('user/home/comment/<int:pk>', views.CommentView.as_view(), name="comment"),

]


#path('', include('django.contrib.auth.urls'))

app/templates/Post.html
{% extends 'base.html' %}

{% load static %}

  {% block title %} {{ title }} {% endblock title %}

  {% block styles %}
    <link href="{% static '/app/post.css' %}" rel="stylesheet" type="text/css"> 
  {% endblock styles %}


  {% block content %}

  <div class="back" >

    <button class="back-btn"><a href="{% url 'app:profile' current_profile.id %}">Back</a></button>
  </div>

  <div id="big-container">
    <div class="header">
      <div class="title">
        <h2>{{ object.title}}  <small> - {{ object.time }}</small></h2>

      </div>

      <div class="buttons">

          <form action="{% url 'app:delete_post' object.id %}" method="POST" id='delete-form'>
            {% csrf_token %}
            {{ form }}
            <input class="delete-btn" type="submit" value="Delete"><button class="edit-btn"><a href="{% url 'app:edit_post' object.id %}">Edit </a></button>
      
          </form>
      
          
      </div>
      
    </div>
    
          <p class="description">
            {% for line in object.description.splitlines %}
            {{ line }}<br>
            {% endfor %}
          </p><br>          
          {% if object.image %}
            <img src="{{ object.image.url }}" id="post_pic" width=600px height=auto ><br>
          {% endif %}

        <div class="like-cmt">
          <p class="likes">{{ object.total_likes }} Likes |  </p>
          <p class="cmts">  {{ object.total_comments }}  Comments </p>
          
          <p><a href="#" class="show-cmts">View all comments </a></p>
        </div>

  </div>
      
      <div>
        <div class="comment-box">
          <h3>Comments</h3>

          {% if object.comments_set.all %}
              {% for c in object.comments_set.all %}
                    
                  <div class=cmt_area>
                      <p class="user"> {{ c.user }} - <small> {{ c.date }}</small> </p>

                      <p class="comment"> >> {{ c.text }} </p>
        
                  </div>
              {% endfor %}
          {% endif %}
        </div>
      </div>
        
  
  {% endblock content %}

{% block scripts %} 
        <script>
            $( document ).ready(function() {

              let display = false
              $(".show-cmts").click(function (e) {

                e.preventDefault();

                if (display===false) {
                    $(".comment-box").slideDown("slow");
                    display=true
                } else {
                    $(".comment-box").slideUp("slow");
                    display=false
                }  
            })


          });

        </script>
{% endblock scripts %}

app/templates/Profile.html
{% extends 'base.html' %}

{% load static %}


{% block title %} {{ title }} {% endblock title %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'app/profile.css' %}">
{% endblock %}

{% block navbar %}
     
           <nav id="nav">
               <ul>
                   <li><a href='{% url "app:home" %}' id="home"><i class="fas fa-home "></i></a></li>
                   <li><a href='{% url "app:addPost" %}' id="addpost"><i class="fas fa-user-plus "></i></a></li>
                   <li><a href='{% url "app:profile" current_profile.pk %}' id="profile"><i class="fas fa-user-circle "></i></a></li>
                   <li><a href='{% url "app:logout" %}' id="logout"><i class="fas fa-sign-out-alt "></i></a></li>
               </ul>
           </nav>
{% endblock navbar %}


{% block content %}

    <div class="container">
        <div id="pic_div">
            <div id="profile_pic">
                {% if profile.image %}
                    <img src= "{{ profile.image.url }}" height=200px width=200px ><br>

                {% endif %}
            </div>

        </div>
        <div id="info_div">
            <div id="user">
                <h1 class="un">{{ profile.user.username }}   </h1> 
                <div id="edit-delete-btn">
                    <form action="{% url 'app:delete_profile' request.user.id %}" method="POST" id='delete-form'>
                        {% csrf_token %}
                        {{ form }}
                        <button type = "submit" class="delete">Delete Profile</button>
                  
                      </form> 
                      <button class="edit"><a href="{% url 'app:editProfile' %}">Edit Profile</a></button> 


                </div>

                <h3 class="fn">{{ profile.fullname }}</h3><br>
                <p class="bio">{{ profile.bio }}</p>

            </div>
            <div id="activities">
                <p >{{ all_posts.count }} Posts </p>
                <p > {{ followers.count }} Followers</p>
            </div>

        </div>

    </div>
    <div id="posts">

        <h2> YOUR POSTS</h2><br>
        <div class="underline"></div>

    
        <div class="pic_container">
            {% for post in all_posts %}

            <div class="pictures">
                <h4 class="post_title">{{ post.title }}</h4>

                <p class="post_desc">{% if post.description|length > 40 %}
                    {{post.description|slice:40}}...
                    {% else  %}
                    {{post.description }}
                {% endif %}</p><br>

                {% if post.image %}
                <a href="{% url 'app:post' post.id %}"><img src="{{ post.image.url }}" width=auto height=180px class="pic"></a><br>
                
                {% endif %}


                
            </div>
            {% endfor %}

        </div>    

    
    </div>

    


{% endblock content %}

app/templates/addPost.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ title }} {% endblock title %}

{% block styles %}
    <link href="{% static '/app/add_post.css' %}" rel="stylesheet" type="text/css"> 
{% endblock styles %}

{% block navbar %}
     
           <nav id="nav">
               <ul>
                   <li><a href='{% url "app:home" %}' id="home"><i class="fas fa-home "></i></a></li>
                   <li><a href='{% url "app:addPost" %}' id="addpost"><i class="fas fa-user-plus "></i></a></li>
                   <li><a href='{% url "app:profile" current_profile.pk %}' id="profile"><i class="fas fa-user-circle "></i></a></li>
                   <li><a href='{% url "app:logout" %}' id="logout"><i class="fas fa-sign-out-alt "></i></a></li>
               </ul>
           </nav>
{% endblock navbar %}

{% block content %}

<h2>ADD POST</h2>
<div class="underline"></div>


<form action='' method='post' enctype='multipart/form-data'>

    {% csrf_token %}

    {{ form.as_p }}

    <input type='submit' value='POST'> <button class="cancel_btn" ><a href="{% url 'app:home' %}">CANCEL</a></button>

</form>

{% endblock content %}

app/templates/base.html
{% load static %}
<!doctype html>
 <html>
   <head>
     <meta charset="utf-8">
     <title>
       {% block title %}
       {{ page_title|default:"Untitled Page" }}
       {% endblock title %}
    </title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"> </script>

    <script src="https://kit.fontawesome.com/f91dab228a.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    {% block scripts %}  {% endblock scripts %}


    {% block styles %} {% endblock styles %}

    <link href="{% static '/app/base.css' %}" rel="stylesheet" type="text/css">
  </head>
  <body>
      <div id="header">

           <div id="logo"><img src="{% static '/images/best.png' %}" height='50px' width='200px' alt="instagram_logo" /></div>
        {% block navbar %}

           <nav id="nav">
               <ul>
                   <li><a href='{% url "app:home" %}' id="home"><i class="fas fa-home "></i></a></li>
                   <li><a href='{% url "app:addPost" %}'><i class="fas fa-user-plus "></i></a></li>
                   <li><a href='{% url "app:profile" current_profile.pk %}'><i class="fas fa-user-circle "></i></a></li>
                   <li><a href='{% url "app:logout" %}'><i class="fas fa-sign-out-alt "></i></a></li>
               </ul>
           </nav>

        {% endblock navbar %}

      </div>
    <section id="main">
      {% block content %}

      {% endblock content %}
    </section>
    <footer id="footer">
   
    </footer>
    

    
  </body>
</html>

app/templates/edit_post.html
{% extends 'base.html' %}

{% load static %}


{% block title %} {{ title }} {% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'app/edit_post.css' %}">
{% endblock %}


{% block content %}

<h2>Edit Post</h2>
<div class="underline"></div>

<form action='' method='post' enctype="multipart/form-data">

    {% csrf_token %}
    <label for="title">Title:</label>
    {{ form.title }}<br>
    <label for="description">Description:</label>
    {{ form.description }}<br>
    <div id="img_row">
        <ul id="img_label">
            <li><label for="image">Change Post Image:</label></li>
            <li>{{ form.image }}</li>
        </ul>
        

        <img id="orig_img" src="{{ form.image.value.url }}" width=400px height="auto">

    </div>
    
    <input type='submit' value='Edit'>  <button class="cancel_btn"><a href="{% url 'app:post' object.id %}">Cancel</a></button>

</form>

{% endblock content %}

app/templates/edit_profile.html
{% extends 'base.html' %}

{% load static %}


{% block title %} {{ title }} {% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'app/edit_profile.css' %}">
{% endblock %}


{% block content %}

<h2>EDIT PROFILE</h2>
<div class="underline"></div>


<form action='' method='post' enctype="multipart/form-data">

    {% csrf_token %}

    <div id="img_row">
        <ul id="img_label">
            <li><label for="image">Profile Picture:</label></li>
            <li class="choice">{{ user_profile_form.image }}</li>
        </ul>
        
        <img id="orig_img" src="{{ user_profile_form.image.value.url }}" width=200px height="200px">

    </div>
    <label for="username">Username:</label>
    {{ user_form.username }}<br>
    <label for="fullname">Name:</label>
    {{ user_profile_form.fullname }}<br>
    <label for="email">Email Address:</label>
    {{ user_form.email }}<br>
    <label for="bio">Bio:</label>
    {{ user_profile_form.bio }}<br>
    
    
    <input type='submit' value='EDIT'>  <button class="cancel_btn"><a href="{% url 'app:profile' current_profile.id %}">CANCEL</a></button>

</form>

{% endblock content %}

app/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {{ title }} {% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'app/home.css' %}">
{% endblock %}

{% block navbar %}
     
           <nav id="nav">
               <ul>
                   <li><a href='{% url "app:home" %}' id="home"><i class="fas fa-home "></i></a></li>
                   <li><a href='{% url "app:addPost" %}' id="addpost"><i class="fas fa-user-plus "></i></a></li>
                   <li><a href='{% url "app:profile" current_profile.pk %}' id="profile"><i class="fas fa-user-circle "></i></a></li>
                   <li><a href='{% url "app:logout" %}' id="logout"><i class="fas fa-sign-out-alt "></i></a></li>
               </ul>
           </nav>
{% endblock navbar %}


{% block content %}
<h2>HOME</h2><br>
<div class="underline"></div>

<div id="post-panel">
    <ul>
        {% for post in object_list %}
        <li>
        <div class="post_container">
            <p class="user">{{ post.user }}  <small>- {{ post.time }}</small></p>

            {% if post.image %}
            <img src="{{ post.image.url }}" width=600px height=auto id="post_pic">
            {% endif %}
            <br>

            <div id="details">
                <p class="title" >{{ post.title }}</p>
                <p class="description">{% for line in post.description.splitlines %}
                    {{ line }}<br>
                    {% endfor %}
                </p><br>

                <div id="like-cmt-share">
                    <form action="{% url 'app:like' %}" method="POST" class='like-form' id='{{ post.id }}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value = {{ post.id }} >
                        
                            <button type="submit" class="like-btn{{post.id}}" id="like-btn" >
                                {% if request.user not in post.likes.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>     
                                
                    </form>
                    <button class="show_comment" id="{{post.id}}" >Comment</button>


                    <button class="share" >Share</button>
                </div>

                <div id="like-cmt-count">
                    <div class="like-count{{post.id}}" id="like-count"> {{post.total_likes}} Likes | </div> 
                    <div class="comments-count{{post.id}}" id="comment-count"> {{post.total_comments}} Comments</div> 
                    
                </div>
            </div>

        </div>

        <div class="comment-box{{post.id}}" id="comment-box">
            <form action="{% url 'app:comment' post.id%}" method="POST" class="comment_form" id='{{ post.id }}'>
                {% csrf_token %}
                <input type="hidden" name="post_id" value = {{ post.id }} >

                {{ comment_form.as_p }}
                <input type="submit" value="comment" id="cmt-btn">
                
                        
            </form>
        </div>
        </li>
        {% endfor %}
    </ul>
</div>

<div id="sugg-panel">
    <p id="sugg_msg">Suggestions for you...</p>

    <ul>
        {% for profile_ in profile_sugg %}

        {% if request.user not in profile_.followers.all%}

        <li>
            <div class="sugg_row">
            <div class="sugg_user">
                <i class="fa fa-user-circle-o fa-lg" aria-hidden="true"></i>

                <h4>{% if profile_.fullname|length > 20 %}
                        {{ profile_.fullname|slice:20 }}...
                    {% else  %}
                        {{ profile_.fullname }}
                    {% endif %}</h4>

                <div class="follow-count{{profile_.id}}" id="follow-count"> {{ profile_.total_followers }} followers</div>

            </div>


            <div class="follow">
                <form action="{% url 'app:follow' %}" method="POST" class='follow-form' id='{{ profile_.id }}'>
                    {% csrf_token %}
                    <input type="hidden" name="profile_id" value = {{ profile_.id }} >
                    
                        <button type="submit" id="follow-btn" class="follow-btn{{profile_.id}}">
                            {% if request.user not in profile_.followers.all %}
                                Follow
                            {% else %}
                                Following
                            {% endif %}
                        </button>
                            
                </form>

            </div>

        </div>
        </li>
        {% endif %}
        {% endfor %}
    </ul>

</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {

            $('.like-form').on('submit', function(event){

                event.preventDefault();
                event.stopPropagation();

                
                const post_id = $(this).attr('id')
                
                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')
                
                let res;
                const likes = $(`.like-count${post_id}`).text()
                const trimCount = parseInt(likes)
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res+" Likes | ")
                    },
                    error: function(response) {
                        console.log('error', response);
                        
                    }

                    
                });

                return false;
            });

            let display=false

            $(".show_comment").click(function(e) {


                post_id = $(this).attr('id')

                if (display===false) {
                    $(`.comment-box${post_id}`).slideDown("slow");
                    display=true;
                }
                else {
                    $(`.comment-box${post_id}`).slideUp("slow");
                    display=false;

                    }
                
            })



            $('.follow-form').on('submit', function(event){

                event.preventDefault();

                const profile_id = $(this).attr('id')

                const followText = $(`.follow-btn${profile_id}`).text()
                const trim = $.trim(followText)

                const url = $(this).attr('action')

                let res;
                const followers = $(`.follow-count${profile_id}`).text()
                const trimCount = parseInt(followers)

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'profile_id':profile_id,
                    },
                    success: function(response) {
                        if(trim === 'Following') {
                            $(`.follow-btn${profile_id}`).text('Follow')
                            res = trimCount - 1
                        } else {
                            $(`.follow-btn${profile_id}`).text('Following')
                            res = trimCount + 1
                        }

                        $(`.follow-count${profile_id}`).text(res+" followers")
                    },
                    error: function(response) {
                        console.log('error', response);
                        
                    }

                });
            });

            $('.comment_form').on('submit', function(e) {
                e.preventDefault();

                const post_id = $(this).attr('id')
                const comments = $(`.comments-count${post_id}`).text()
                var Count = parseInt(comments)


                $.ajax({
                    url : $(this).attr('action') ,
                    type: "POST",
                    data: $(this).serialize(),
                    success: function (data) {
                        $(`.comment-box${post_id}`).slideUp("slow");
                        Count = Count + 1;
                        $(`.comments-count${post_id}`).text(Count+" Comments")


                    },
                    error: function (jXHR, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
        });
    });
            

        });
    </script>
{% endblock scripts %}

app/templates/signup.html
{% load static %} 

{% if invalid %}
    <script> 
        var invalid=false
        alert('Sorry! Something went wrong ....')

    </script>
{% endif %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    <style>
        body {
            background-image: linear-gradient(145deg,rgb(247, 247, 131), rgb(240, 171, 45), rgba(241, 53, 53), rgba(150, 22, 71),rgb(13, 13, 122));
            background-repeat: no-repeat;
            background-size:100vw 100vh;
        }
        .big_con {
            position: fixed;
            top: 35%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .container1, .container2{
            width:340px;
            background-color:rgba(255, 255, 255, 0.25);
            text-align:center;
            padding:12px;
            margin:15px;
            opacity:0.75;
            position:relative;
            z-index:1;
            /*border: 1px solid black;*/
        }
        #logo{
            text-align:center;
            margin:30px;
            opacity:1;
        }
        
        input {
            margin: 7px 20px 7px 20px;
            width: 250px;
            padding:5px;
            outline:none;
            border-radius:3px;
            border:1px solid rgb(63, 62, 62);
            opacity:0.65;


        }
        input:focus {
            background-color: rgb(184, 220, 238);
            outline:none;
            border:1px solid rgb(70, 69, 69);
        }
        .btn {
            width:264px;
            margin: 30px 20px;
            background-color:rgb(82, 102, 140);
            color:white;
            border:1px solid rgb(31, 69, 104);
            border-radius: 3px;
            opacity: 0.95;
        }
        .btn:focus {
            border:1px solid black;
            background-color:rgb(24, 83, 131);
        }
        p{
            font-size:17px;
        }
        a{  
            font-size:18px;
            text-decoration: underline 1px rgb(24,79,182);
            color:rgb(24, 79, 182);
        }
        a:hover{
            text-decoration :underline solid rgb(29, 71, 110);
        }
        .container3 {
            margin:5px;
            height: 200px;
            width: 150px;
            background-color: rgb(231, 222, 222,0);
            position:relative;
            top: 205px;
            border-left: 2px solid rgba(0, 0, 0, 0.4);
            border-top: 2px solid rgba(0, 0, 0, 0.4);
        }
        .container4 {
            margin:5px;
            height: 50px;
            width: 150px;
            background-color: rgb(231, 222, 222,0);
            position:relative;
            z-index:-1;
            bottom: 60px;
            border-right: 2px solid rgba(0, 0, 0, 0.4);
            border-bottom: 2px solid rgba(0, 0, 0, 0.4);
            float:right;

        }
        @media only screen and (max-width: 500px) {
            .container1, .container2{
                width:260px;
                background-color:rgba(255, 255, 255, 0.25);
                /*background-color:rgba(168, 109, 109, 0.25);*/
                padding:5px;
                margin:15px;
            }
            input {
                margin: 7px 20px 7px 20px;
                width: 180px;
                padding:5px;
            }
            #logo{
                margin:20px;
            }
            #logo img{
                width:140px;
            }
            .btn{
                width:180px;
            }

        }
        @media only screen and (max-width: 300px) {
            .container1, .container2{
                width:210px;
                background-color:rgba(255, 255, 255, 0.25);
                padding:3px;
                margin:10px;
            }
            input {
                margin: 7px 20px 7px 20px;
                width: 162px;
                padding:5px;
            }
            #logo{
                margin:20px;
            }
            #logo img{
                width:120px;
            }
            .btn{
                width:162px;
            }

        }

    </style>

</head>
<body>

    
    <div class='big_con'>

        <div class="container3"></div>

        <div class='container1'>
            <div id="logo">

                <img src="{% static 'images/name_logo.png' %}" height='auto' width='175px'/>
            </div>
            
            <form action='' method='post' autocomplete='off'>
                {% csrf_token %}

                {% for field in profile_form %}
                    <div class="fieldWrapper">
                    {{ field }}
                
                    </div>
                {% endfor %}

                {% for field in user_form %}
                    <div class="fieldWrapper">
                    {{ field }}
                
                    </div>
                {% endfor %}

                <input type='submit' class='btn' value='Sign Up'>

            </form>
            <div class='error'>{{form.errors.username}}</div>


        </div>
        <div class='container2'>
            <p>Have an account?<a href="{% url 'app:user_login' %}"> Login</a></p>
        </div>

        <div class="container4"></div>


    </div>
</body>
</html>

app/templates/sugg.html
{% block content %}
<ul>
    {% for profile_ in object_list %}

    <li>
        {{profile_.fullname}}<br>
        <form action="{% url 'app:follow' %}" method="POST" class='follow-form' id='{{ profile_.id }}'>
            {% csrf_token %}
            <input type="hidden" name="profile_id" value = {{ profile_.id }} >
            
                <button type="submit" class="follow-btn{{profile_.id}}">
                    {% if request.user not in profile_.followers.all %}
                        Follow
                    {% else %}
                        Following
                    {% endif %}
                </button>
                <div class="ui grid">
                    <div class="column">
                        <div class="follow-count{{profile_.id}}"> {{ profile_.total_followers }} </div>
                    </div>
                    <div class="column">
                        followers
                    </div>
                </div>
        </form>
    </li>
    {% endfor %}
</ul>

<script>
    $( document ).ready(function() {
        $('.follow-form').on('submit', function(event){

            event.preventDefault();


            const profile_id = $(this).attr('id')

            const followText = $(`.follow-btn${profile_id}`).text()
            const trim = $.trim(followText)

            const url = $(this).attr('action')

            let res;
            const followers = $(`.follow-count${profile_id}`).text()
            const trimCount = parseInt(followers)

            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    'post_id':profile_id,
                },
                success: function(response) {
                    if(trim === 'Following') {
                        $(`.follow-btn${profile_id}`).text('Follow')
                        res = trimCount - 1
                    } else {
                        $(`.follow-btn${profile_id}`).text('Following')
                        res = trimCount + 1
                    }

                    $(`.follow-count${profile_id}`).text(res)
                },
                error: function(response) {
                    console.log('error', response);
                    
                }

                
            });


            });



});
</script>

{% endblock content %}